# druid数据源配置
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    druid:
      master:
        url: jdbc:mysql://127.0.0.1:3306/xd11cc_single?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai
        username: root
        password: xd11cc@1216
      slave:
        enable: false
        url:
        username:
        password:
      # 初始连接数
      initial-size: 5
      # 最小连接池数量
      min-idle: 10
      # 最大连接池数量
      max-active: 20
      # 配置获取连接等待超时的时间
      max-wait: 60000
      # 配置连接超时时间
      connect-timeout: 30000
      # 配置网络超时时间
      socket-timeout: 60000
      # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      time-between-eviction-runs-millis: 60000
      # 配置一个连接在池中最小生存的时间，单位是毫秒
      min-evictable-idle-time-millis: 300000
      # 配置一个连接在池中最大生存的时间，单位是毫秒
      max-evictable-idle-time-millis: 900000
      # 配置检测连接是否有效
      validation-query: SELECT 1 FROM DUAL
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      web-stat-filter:
        enabled: true
      stat-view-servlet:
        enabled: true
        # 设置白名单，不填则允许所有访问
        allow:
        url-pattern: /druid/*
        # 控制台管理用户名和密码
        login-username: xd11cc
        login-password: xd11cc@1216
      filter:
        stat:
          enabled: true
          # 慢SQL记录
          log-slow-sql: true
          slow-sql-millis: 2000
          merge-sql: true
        wall:
          config:
            multi-statement-allow: true

  # redis配置
  redis:
    host: 127.0.0.1
    port: 6379
    database: 0
    password: xd11cc@1216

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

# swagger配置
swagger:
  title: 后端API
  description: 单体项目框架搭建
  version: v1.0.0

# security白名单配置
security:
  permit-all-urls:
    # 静态资源
    - /**/**.html
    - /**/**.css
    - /**/**.js
    # swagger白名单配置
    - /doc.html
    - /swagger-ui.html
    - /webjars/**
    - /swagger-resources/**
    - /v2/api-docs/**
    - /favicon.ico
    # druid监控地址
    - /druid/**
    # 登录相关白名单
    - /user/loginByPassword
