server:
  port: 10001
  servlet:
    context-path: /xd11cc

spring:
  application:
    name: xd11cc-single
  profiles:
#    active: @profileActive@
    active: dev
  jackson:
    time-zone: Asia/Shanghai
    date-format: yyyy-MM-dd MM:dd:ss
  mvc:
    pathmatch:
      # 由于spring默认的url匹配策略是PATH_PATTERN_PARSER，与security匹配规则不一致可能会导致安全策略失效
      matching-strategy: ant_path_matcher
  main:
    allow-circular-references: true # 开启循环依赖支持

logging:
  level:
    com.xd11cc.*: debug

mybatis-plus:
  global-config:
    db-config:
      logic-delete-field: del_flag # 全局逻辑删除字段名
      id-type: auto
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

# 分页插件
pagehelper:
  helper-dialect: mysql
  reasonable: true

# netty配置
netty:
  websocket:
    port: 12001
    reader-idle-time: 30
    writer-idle-time: 60
    web-socket-path: /ws
    max-frame-length: 65536

# swagger配置
swagger:
  title: 后端API
  description: 单体项目框架搭建
  version: v1.0.0

# security白名单配置
security:
  permit-all-urls:
    # 静态资源
    - /**/**.html
    - /**/**.css
    - /**/**.js
    # swagger白名单配置
    - /doc.html
    - /swagger-ui.html
    - /webjars/**
    - /swagger-resources/**
    - /v2/api-docs/**
    - /favicon.ico
    - /csrf
    - /
    # druid监控地址
    - /druid/**
    # 登录相关白名单
    - /login/loginByPassword
    - /login/getCaptcha

# 需要忽略租户的表
tenant:
  ignoreTables:
    - system_menu
    - system_dict_type
  ignoreUrls:
