spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/xd11cc_single?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    username: root
    password: xd11cc@1216
    driver-class-name: com.mysql.cj.jdbc.Driver

# redis配置
  redis:
    host: 127.0.0.1
    port: 6379
    database: 0
    password: xd11cc@1216

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

# swagger配置
swagger:
  enabled: true
  pathMapping: /dev-api
  title: 后端API
  description: 单体项目框架搭建
  version: v1.0.0

# security白名单配置
security:
  permit-all-urls:
    # swagger白名单配置
    - /doc.html
    - /swagger-ui.html
    - /webjars/**
    - /swagger-resources/**
    - /v2/api-docs/**
    - /favicon.ico
    # 登录相关白名单
    - /user/loginByPassword
